db/migrations/*                /usr/lib/multiflexi-database/migrations/
db/seeds/*                     /usr/lib/multiflexi-database/seeds/
debian/conf/phinx-adapter.php  /usr/lib/multiflexi-database/
debian/tmp/composer.json       /usr/lib/multiflexi-database/
bin/multiflexi-migrator        /usr/bin/
bin/update-multiflexi-env   /usr/bin/
multiflexi-migrations.svg	usr/share/icons/hicolor/scalable/apps/
debian/cz.vitexsoftware.multiflexi_migrations.metainfo.xml	usr/share/metainfo/
