.TH MULTIFLEXI-MIGRATOR 1 "July 2025" "Vitex Software" "User Commands"
.SH NAME
multiflexi-migrator \- databázová migrace pro MultiFlexi
.SH SYNOPSIS
.B multiflexi-migrator
[\fIOPTIONS\fR]
.SH DESCRIPTION
.B multiflexi-migrator
je nástroj pro správu a provádění databázových migrací v rámci systému MultiFlexi.

Po instalaci balíčku multiflexi-database je tento nástroj automaticky spuštěn pro nastavení a aktualizaci databázové struktury.

.SH OPTIONS
Bez parametrů provede všechny dostupné migrace.

.SH EXAMPLES
.PP
.B multiflexi-migrator
.PP
Spustí všechny migrace.

.SH AUTHOR
Vítězslav Dvořák <info@vitexsoftware.cz>

.SH SEE ALSO
.BR multiflexi-phinx (1), multiflexi-json2app (1)
