#!/bin/sh

set -e
#set -x

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm.mysql ]; then
    . /usr/share/dbconfig-common/dpkg/postrm.mysql
    dbc_go multiflexi "$@"
fi


if [ "$1" = "purge" ]; then
	rm -f /etc/multiflexi/database.env
	if command -v ucf >/dev/null; then
		ucf --purge /etc/multiflexi/database.env
		ucfr --purge multiflexi /etc/multiflexi/database.env
	fi
fi

#DEBHELPER#
